name: Angular CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Build Angular App
        id: build-prod
        run: npm run build --prod
        
      - name: Archive Build Artifacts
        id: ng-dist
        uses: actions/upload-artifact@v3.1.3
        with:
          name: angular-build
          path: dist/
          
      - name: Deploy to Production
        id: deploy-to-production
        if: steps.build-prod.outcome == 'success'
        run: echo "Deployment to production would occur here"
        
      - name: Deploy Failure
        if: failure() && steps.deploy-to-production.outcome == 'failure'
        run: echo "Deploy failed"

      
