name: Angular CICD
on:
  push:
    # paths:
    #   - 'ng-security/**'
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Change Directory to Angular Project
        run: cd ng-security

      - name: Install Dependencies
        run: |
          cd ng-security
          npm ci

      # - name: Run Tests
      #   run: |
      #     cd ng-security
      #     npm test

      - name: Build Angular App
        id: build-prod
        run: |
          cd ng-security
          npm run build --prod
        
      - name: Archive Build Artifacts
        id: ng-dist
        uses: actions/upload-artifact@v3.1.3
        with:
          name: angular-build
          path: ng-security/dist/
          
     
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: angular-build
          path: dist/ 

      - name: Deploy to Production
        id: deploy-to-production
        if: success()
        run: echo "Deployment to production would occur here"
      
      - name: Deploy Failure
        if: failure() && steps.deploy-to-production.outcome == 'failure'
        run: echo "Deploy failed"


      
