name: Spring Boot Continuous Integration
on:
  push:
    paths:
      - "manufacturing-manager-api/**"
      - ".github/**/java*.yml"
    branches:
      - main

env:
  PROJECT_DIRECTORY: "manufacturing-manager-api"
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: |
          cd ${{env.PROJECT_DIRECTORY}}
          mvn -B package --file pom.xml
