name: Spring Boot Continuous Integration
on:
  push:
    paths:
      - "manufacturing-manager-api/**"
      - ".github/**/java*.yml"
    branches:
      - main

env:
  PROJECT_DIRECTORY: "manufacturing-manager-api"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run docker compose
        run: |
         cd ${{ env.PROJECT_DIRECTORY }}
         docker-compose up -d

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Grant execute permission to mvnw
        run: chmod +x mvnw
        working-directory: ${{ env.PROJECT_DIRECTORY }}

      - name: Build with Maven
        run: |
          cd ${{env.PROJECT_DIRECTORY}}
          ls 
          ./mvnw -B package --file pom.xml
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
          POSTGRES_DB: "mma"
