name: Spring Boot Continuous Integration
on:
  push:
    paths:
      - "manufacturing-manager-api/**"
      - ".github/**/java*.yml"
    branches:
      - main

env:
  PROJECT_DIRECTORY: "manufacturing-manager-api"

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: openjdk:17
    #   options: --mount=type=cache,target=/root/.m2/repository

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: "abdulrehman"
          POSTGRES_PASSWORD: "Abdulrehman#1"
          POSTGRES_DB: "mma"
        #   PGDATA: /data/postgres
        # volumes:
        #   - postgres:/data/postgres
      # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 100s
          --health-timeout 50s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Grant execute permission to mvnw
        run: chmod +x mvnw
        working-directory: ${{ env.PROJECT_DIRECTORY }}

      - name: Build with Maven
        run: |
          cd ${{env.PROJECT_DIRECTORY}}
          ls 
          ./mvnw -B package --file pom.xml
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
          POSTGRES_DB: "mma"
